AllCops:
  Exclude:
    - 'spec/fixtures/orders/parsed_marketplace_order.rb'
    - 'spec/factories/orders.rb'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
Layout/LineLength:
  Max: 120
  Enabled: true
Metrics/MethodLength:
  Max: 12
  Enabled: true
Metrics/ClassLength:
  Max: 150
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'