Layout/LineLength:
  Max: 120
  Enabled: true
Metrics/MethodLength:
  Max: 12
  Enabled: true
Metrics/ClassLength:
  Max: 150
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'